template_path: remote/cfn-cr-sc-bucket-policy.yaml
stack_name: cfn-cr-sc-bucket-policy
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
hooks:
  before_launch:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/cfn-cr-sc-bucket-policy/sc113/cfn-cr-sc-bucket-policy.yaml --create-dirs -o templates/remote/cfn-cr-sc-bucket-policy.yaml"
