AWSTemplateFormatVersion: '2010-09-09'
Description: 'Workflows Linux EC2 ServiceCatalog product with Jumpcloud integration.'
Parameters:
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
  ProductName:
    Type: String
    Description: Name of the product that will be visible to the end user
    Default: 'EC2: Ubuntu Linux with Workflow Software'
  StackDatetime:
    Type: String
    Description: Last updated date and time of product
    Default: ''
  ReplaceProvisioningArtifacts:
    Type: String
    Description: "Whether to keep or replace the provisioning artifact identifier on update"
    Default: 'false'
  PortfolioId:
    Type: String
    Description: ID of the portfolio that will contain this product
Resources:
  ScEc2LinuxJumpcloudWorkflowsProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
            - E3003
            - W2001
    Properties:
      Name: !Ref ProductName
      Description: This product builds one Linux EC2 instance using an Ubuntu AMI
        with workflows software installed. Maintained by Sage Bionetworks.
      ProvisioningArtifactParameters:
        - Description: !Sub 'Tthyer development version. Last portfolio update occurred at ${StackDatetime}.'
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}ec2/sc-ec2-linux-workflows-tthyer.yaml'
          Name: 'dev'
      'Fn::Transform':
        Name: 'AWS::Include'
        Parameters:
          # source: https://github.com/Sage-Bionetworks/admincentral-infra/blob/master/templates/cfn-snippets-bucket.yaml
          Location: "s3://cfn-snippets-bucket-cloudformationsnippetsbucket-elu83sv8ocdz/scipool/products.yaml"
      ReplaceProvisioningArtifacts: !Ref ReplaceProvisioningArtifacts
  Associateec2linux:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref 'ScEc2LinuxJumpcloudWorkflowsProduct'
  constraintec2linux:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: Associateec2linux
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId: !Ref 'ScEc2LinuxJumpcloudWorkflowsProduct'
      RoleArn: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-ec2vpc-launchrole-LaunchRoleArn'
Outputs:
  ProductId:
    Value: !Ref 'ScEc2LinuxJumpcloudWorkflowsProduct'
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ProductId'
